### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by Dreddik** [mayoff/uiimage-from-animated-gif#10]
Here is example gif. After decoding it and show on the screen, memory usage increase to 95 mb in empty application.
Example code http://paste.org.ru/?ix5w5s
![2](https://cloud.githubusercontent.com/assets/1570382/2623367/6f3605e2-bce9-11e3-9029-8a77a89deb4c.gif)

How can I decrease memory usage?

**Comment by drico** [comment]
I agree this is a main issue, particularly in a keyboard extention where the memory usage is limited to 40MB.

**Comment by KimDarren** [comment]
@Dreddik How could you solve this problem?

**Comment by mayoff** [comment]
If you need to display this sort of animated GIF, I recommend you use [`FLAnimatedImage`](https://github.com/Flipboard/FLAnimatedImage) instead of this project. I'm not going to solve this problem.

**Comment by KimDarren** [comment]
@mayoff 
Thank you for the advice!
I tried to use `FLAnimatedImage`, your project's performance was much better..
Do you know any other way to use GIF in iOS?

**Comment by mayoff** [comment]
No.

**Comment by KimDarren** [comment]
@mayoff Okay. Thank you so much 😄
