### ISSUE TITLE
Converting back to data?

### ISSUE THREAD

**Issue by benjaminhallock** [mayoff/uiimage-from-animated-gif#17]
Finally got the gif off the pastboard and onto the screen. Problem is I can't get it off the textView and back into NSData. Using UIImagePNGRep... doesn't work. How can I convert the image back to data without saving it in a property?

**Comment by mayoff** [comment]
If you're looking for a way to write out a (small) animated GIF, read this answer: http://stackoverflow.com/a/14916097/77567

**Comment by benjaminhallock** [comment]
I just saved the data to a property, not the best solution if your pulling it off of a UITextView.
